name 'docker-registry'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docker-registry'
long_description 'Installs/Configures docker-registry'
version '0.1.0'

depends 'apt', '~> 2.9.2'
depends 'poise-python', '~> 1.2.1'
